name: Find Linear Issue in Pull Request

env:
  ACTIONS_STEP_DEBUG: true

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: ["opened", "edited", "reopened", "synchronize"]

jobs:
  find-linear-issue-by-pull-request-data:
    runs-on: ubuntu-latest
    name: A test job

    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout action repo
        uses: actions/checkout@v3

      - name: Find the Linear Issue
        id: findIssue
        uses: ./ # Uses an action in the root directory
        with:
          linear-api-key: ${{ secrets.LINEAR_API_KEY }}

      - name: Create comment in PR with Linear Issue link
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ```yaml
            ${{ fromJson(steps.findIssue.outputs.linear-issue) }}
            ```
